# Generated by Django 3.0.5 on 2020-05-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_export_celery', '0006_auto_20191125_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importjob',
            name='model',
            field=models.CharField(choices=[('Contact', 'Contact')], max_length=160, verbose_name='Name of model to import to'),
        ),
    ]
