# Generated by Django 3.0.5 on 2020-05-15 18:44

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(default='', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('is_valid', models.BooleanField()),
                ('campaign_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='email_import.Campaign')),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=255)),
                ('email_text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('campaigns', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='email_import.Campaign')),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_opened', models.BooleanField(default=False)),
                ('emails_count', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('campaigns', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='email_import.Campaign')),
            ],
        ),
        migrations.CreateModel(
            name='LastSending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=254)),
                ('last_email', models.DateField()),
                ('contacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='email_import.Contact')),
            ],
        ),
    ]
