# Generated by Django 3.0.5 on 2020-04-24 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('email_import', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='Last_sending',
            new_name='LastSending',
        ),
        migrations.DeleteModel(
            name='Campaigns',
        ),
        migrations.RemoveField(
            model_name='templates',
            name='template_name',
        ),
        migrations.AddField(
            model_name='templates',
            name='email_text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='campaign_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='email_import.Campaign'),
        ),
    ]
