# Generated by Django 3.0.5 on 2020-04-26 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('email_import', '0002_auto_20200424_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('is_valid', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=255)),
                ('email_text', models.TextField(default='')),
            ],
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='campaign_name',
        ),
        migrations.DeleteModel(
            name='Templates',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='lastsending',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='statistic',
            name='campaigns',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='email_import.Campaign'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='emails_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statistic',
            name='is_opened',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='template',
            name='campaigns',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='email_import.Campaign'),
        ),
        migrations.AddField(
            model_name='contact',
            name='campaign_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='email_import.Campaign'),
        ),
        migrations.AlterField(
            model_name='lastsending',
            name='contacts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='email_import.Contact'),
        ),
        migrations.DeleteModel(
            name='Contacts',
        ),
    ]
