# Generated by Django 3.0.5 on 2020-05-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_import', '0002_sending'),
    ]

    operations = [
        migrations.AddField(
            model_name='sending',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('pending', 'pending'), ('done', 'done')], default='new', max_length=50),
        ),
    ]
