# Generated by Django 3.0.5 on 2020-05-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_import', '0004_template_email_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='email_sender',
            field=models.CharField(default='', max_length=255),
        ),
    ]
