# Generated by Django 3.0.5 on 2020-05-20 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_import', '0005_auto_20200518_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='email_sender',
        ),
    ]
