# Generated by Django 3.0.5 on 2020-04-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_import', '0008_auto_20200425_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='emails_count',
            field=models.IntegerField(default=0),
        ),
    ]
